### ISSUE TITLE
About the type of youbot's Onboard computer

### ISSUE THREAD

**Issue by 7huan** [ut-ims-robotics/youbot#1]
Dear Mihkelson, 
  Thank you for you code. It My Onboard computer is running Ubuntu 12.04 + ROS Hydro. It seems not adapt to your code. When I try to run your code, **roslaunch youbot_moveit demo.launch** .There is a mistake on the terminal of the youbot, seems like this:
**datatype/md5sum [control_msgs/FollowJointTrajectoryActionResult/c4fb3b000dc9da4fd99699380efcc5d9], but our version has [control_msgs/FollowJointTrajectoryActionResult/bce83d50f7bb28226801436caf0e2043]. Dropping connection.**
  It seems like my Onboard computer have to run Ubuntu 14.04 + ROS Indigo? Can I change my Onboard computer to Ubuntu 14.04 + ROS Indigo from Ubuntu 12.04 + ROS Hydro? It will make my youbot can't be used,if I do this? Or, there are some easier solutions to solve this problem?
  It would be nice if you could provide a bit more information on the my problem.Thank you, sir!

**Comment by TianbaoZhang001** [comment]
Hi,
With such md5sum error, please check this [answer](http://answers.ros.org/question/10628/running-processes-on-different-machines-causes-md5sum-incompatibility-issue/?answer=15700#post-id-15700). It seems that you need to have the same version, i.e. Ubuntu 14.04 + ROS Indigo.
We are using this configuration in youbot by reinstalling Ubuntu and ROS. The youbot driver and ROS wrapper can be found online. Works just fine. 
Good luck!

**Comment by 7huan** [comment]
Thank you very much for your answer！

**Comment by 7huan** [comment]
Thank you, sir!
Best wishes for you!

At 2017-05-15 15:02:22, "mark2n" <notifications@github.com> wrote:


Hi,
With such md5sum error, please check this answer. It seems that you need to have the same version, i.e. Ubuntu 14.04 + ROS Indigo.
We are using this configuration in youbot by reinstalling Ubuntu and ROS. The youbot driver and ROS wrapper can be found online. Works just fine.
Good luck!

**Comment by TianbaoZhang001** [comment]
You are so welcome!
